---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dinar397/public_html/kasbaru
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH